-- ============================================
-- POSTS
-- Denormalized data model with embedded user data
-- Supabase / PostgreSQL
-- ============================================

DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    caption TEXT NOT NULL,
    image TEXT NOT NULL,

    "userName" TEXT NOT NULL,
    "userMail" TEXT NOT NULL,
    "userTitle" TEXT NOT NULL,
    "userImage" TEXT NOT NULL
);

-- ============================================
-- SEED DATA
-- 10 posts created by 5 different users
-- User data is intentionally repeated
-- ============================================

INSERT INTO posts (
    caption,
    image,
    "userName",
    "userMail",
    "userTitle",
    "userImage"
)
VALUES
    -- Rasmus Cederdorff (3 posts)
    (
        'Exploring the streets of Aarhus.',
        'https://images.unsplash.com/photo-1559070169-a3077159ee16?auto=format&fit=crop&w=1200&q=80',
        'Rasmus Cederdorff',
        'race@eaaa.dk',
        'Senior Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/race.webp'
    ),
    (
        'Modern architecture at Aarhus Ø.',
        'https://images.unsplash.com/photo-1625773842107-7e842ff1db2f?auto=format&fit=crop&w=1200&q=80',
        'Rasmus Cederdorff',
        'race@eaaa.dk',
        'Senior Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/race.webp'
    ),
    (
        'A quiet evening around Dokk1.',
        'https://images.unsplash.com/photo-1537177080923-1fb15084a8cb?auto=format&fit=crop&w=1200&q=80',
        'Rasmus Cederdorff',
        'race@eaaa.dk',
        'Senior Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/race.webp'
    ),

    -- Maria Louise Bendixen (2 posts)
    (
        'A summer afternoon in Aarhus.',
        'https://images.unsplash.com/photo-1573997953524-efed43db70a0?auto=format&fit=crop&w=1200&q=80',
        'Maria Louise Bendixen',
        'mlbe@eaaa.dk',
        'Senior Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/mlbe.webp'
    ),
    (
        'Architecture and city life at Aarhus Ø.',
        'https://images.unsplash.com/photo-1558443336-dbb3de50b8b2?auto=format&fit=crop&w=1200&q=80',
        'Maria Louise Bendixen',
        'mlbe@eaaa.dk',
        'Senior Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/mlbe.webp'
    ),

    -- Birgitte Kirk Iversen (2 posts)
    (
        'A walk through the centre of Aarhus.',
        'https://images.unsplash.com/photo-1612624629424-ddde915d3dc5?auto=format&fit=crop&w=1200&q=80',
        'Birgitte Kirk Iversen',
        'bki@eaaa.dk',
        'Senior Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/bki.webp'
    ),
    (
        'A view across the rooftops of Aarhus.',
        'https://images.unsplash.com/photo-1661505216710-32316e7b5bb3?auto=format&fit=crop&w=1200&q=80',
        'Birgitte Kirk Iversen',
        'bki@eaaa.dk',
        'Senior Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/bki.webp'
    ),

    -- Lars Bøge Eskildsen (2 posts)
    (
        'Enjoying a quiet moment in the city.',
        'https://images.unsplash.com/photo-1545319261-f3760f9dd64d?auto=format&fit=crop&w=1200&q=80',
        'Lars Bøge Eskildsen',
        'laes@eaaa.dk',
        'Senior Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/laes.webp'
    ),
    (
        'Summer by the water in Aarhus.',
        'https://images.unsplash.com/photo-1566241832378-917a0f30db2c?auto=format&fit=crop&w=1200&q=80',
        'Lars Bøge Eskildsen',
        'laes@eaaa.dk',
        'Senior Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/laes.webp'
    ),

    -- Nikolaj Krogh Kjær-Rasmussen (1 post)
    (
        'Colourful reflections across the city.',
        'https://images.unsplash.com/photo-1548940740-204726a19be3?auto=format&fit=crop&w=1200&q=80',
        'Nikolaj Krogh Kjær-Rasmussen',
        'nkkr@eaaa.dk',
        'Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/nkkr.webp'
    );