-- ============================================
-- USERS + POSTS
-- Normalized one-to-many data model
-- Supabase / PostgreSQL
-- ============================================

DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;

-- ============================================
-- USERS
-- ============================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    mail TEXT NOT NULL,
    title TEXT NOT NULL,
    image TEXT NOT NULL
);

-- ============================================
-- POSTS
-- ============================================

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    caption TEXT NOT NULL,
    image TEXT NOT NULL,
    "userId" BIGINT NOT NULL,

    CONSTRAINT "posts_userId_fkey"
        FOREIGN KEY ("userId")
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- ============================================
-- USERS SEED DATA
-- ============================================

INSERT INTO users (
    name,
    mail,
    title,
    image
)
VALUES
    (
        'Rasmus Cederdorff',
        'race@eaaa.dk',
        'Senior Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/race.webp'
    ),
    (
        'Maria Louise Bendixen',
        'mlbe@eaaa.dk',
        'Senior Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/mlbe.webp'
    ),
    (
        'Birgitte Kirk Iversen',
        'bki@eaaa.dk',
        'Senior Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/bki.webp'
    ),
    (
        'Lars Bøge Eskildsen',
        'laes@eaaa.dk',
        'Senior Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/laes.webp'
    ),
    (
        'Nikolaj Krogh Kjær-Rasmussen',
        'nkkr@eaaa.dk',
        'Lecturer',
        'https://raw.githubusercontent.com/cederdorff/race/master/images/users/nkkr.webp'
    );

-- ============================================
-- POSTS SEED DATA
-- Same 10 posts as before
-- ============================================

INSERT INTO posts (
    caption,
    image,
    "userId"
)
VALUES
    (
        'Exploring the streets of Aarhus.',
        'https://images.unsplash.com/photo-1559070169-a3077159ee16?auto=format&fit=crop&w=1200&q=80',
        1
    ),
    (
        'Modern architecture at Aarhus Ø.',
        'https://images.unsplash.com/photo-1625773842107-7e842ff1db2f?auto=format&fit=crop&w=1200&q=80',
        1
    ),
    (
        'A quiet evening around Dokk1.',
        'https://images.unsplash.com/photo-1537177080923-1fb15084a8cb?auto=format&fit=crop&w=1200&q=80',
        1
    ),
    (
        'A summer afternoon in Aarhus.',
        'https://images.unsplash.com/photo-1573997953524-efed43db70a0?auto=format&fit=crop&w=1200&q=80',
        2
    ),
    (
        'Architecture and city life at Aarhus Ø.',
        'https://images.unsplash.com/photo-1558443336-dbb3de50b8b2?auto=format&fit=crop&w=1200&q=80',
        2
    ),
    (
        'A walk through the centre of Aarhus.',
        'https://images.unsplash.com/photo-1612624629424-ddde915d3dc5?auto=format&fit=crop&w=1200&q=80',
        3
    ),
    (
        'A view across the rooftops of Aarhus.',
        'https://images.unsplash.com/photo-1661505216710-32316e7b5bb3?auto=format&fit=crop&w=1200&q=80',
        3
    ),
    (
        'Enjoying a quiet moment in the city.',
        'https://images.unsplash.com/photo-1545319261-f3760f9dd64d?auto=format&fit=crop&w=1200&q=80',
        4
    ),
    (
        'Summer by the water in Aarhus.',
        'https://images.unsplash.com/photo-1566241832378-917a0f30db2c?auto=format&fit=crop&w=1200&q=80',
        4
    ),
    (
        'Colourful reflections across the city.',
        'https://images.unsplash.com/photo-1548940740-204726a19be3?auto=format&fit=crop&w=1200&q=80',
        5
    );